### ISSUE TITLE
Permission error on Android APIs above 29

### ISSUE THREAD

**Issue by MJ1998** [google-research/CVD-paper-mobile-camera-example#1]
App says unable to get permissions.
![Screenshot 2023-09-19 at 12 23 50 PM](https://github.com/google-research/CVD-paper-mobile-camera-example/assets/22965002/5991e61a-5209-472a-8f40-98cafd9b9ee4)

This is on Pixel 4 API 31.

**Comment by themonk911** [comment]
Ah this is the error I was getting when trying to use the app.

**Comment by MJ1998** [comment]
> Ah this is the error I was getting when trying to use the app.

Please feel free to raise issues! We will be happy to address them.
