### ISSUE TITLE
Add API to fetch List of UploadRequest based on List of Patient Ids

### ISSUE THREAD

**Issue by khyativyasargus** [google-research/CVD-paper-mobile-camera-example#114]
This is required to display the media file upload status in the app.

@MJ1998

**Comment by MJ1998** [comment]
Thanks Khyati. 

I am thinking of adding following API
`suspend fun listUploadRequestForParticipants(
    participants: List<String>
  ): List<Pair<String, List<UploadRequest>>>`
  
  Should this help ?
