### ISSUE TITLE
Status update and Files deletion not working after successful upload

### ISSUE THREAD

**Issue by khyativyasargus** [google-research/CVD-paper-mobile-camera-example#24]
After Successful upload of PPG video and image data to minIO blob storage, Zip files should be deleted from local storage to free space & Status should be updated to success in ResourceInfo, CameraInfo & UploadRequest Entities in room storage , but instead it remains Pending!
Due to this it retries uploading again while syncing next time and gives FileNotFound Exception.

@MJ1998

**Comment by MJ1998** [comment]
It gives FileNotFound because the zipped files get deleted after successful upload.
Regarding the Status being updated I see an OOM Exception in case of large files. This results in worker failure. 
Looking into this.

**Comment by MJ1998** [comment]
The upload is not crashing but the db records are still not udpating.
