### ISSUE TITLE
Source Image rotation issue

### ISSUE THREAD

**Issue by khyativyasargus** [google-research/CVD-paper-mobile-camera-example#41]
While Capturing image , it is being stored with some rotation (probably 90 degree).

![Participant3e24c6d9-a2dc-4fff-8983-270824d8711a_FingernailsOpen_0_1700641076933_v2s1](https://github.com/google-research/CVD-paper-mobile-camera-example/assets/121015652/ba2045da-a702-4f7d-a463-c0baba3709de)

@MJ1998

**Comment by MJ1998** [comment]
Does the app have unlocked orientation?

By default camerax stores image in the orientation it was captured. 

Is it possibel that while capturing the orientation of the app was changed ?

Can you try by locking app's orientation ? Just to check.
`android:screenOrientation="portrait"` in AndroidManifest.

**Comment by MJ1998** [comment]
I can replicate it and its not really an issue.

Android stores every image, no matter if it is taken in landscape or in portrait, in landscape mode. It also stores metadata that tells you if the image should be displayed in portrait or landscape.

**Comment by khyativyasargus** [comment]
okay @MJ1998  I will give it a look again and let you know.

**Comment by MJ1998** [comment]
Having locked orientation will not save Exif properties for the captured files . 

May wanna check that.

**Comment by MJ1998** [comment]
@khyativyasargus is this still open ?
