### ISSUE TITLE
Provide Bearer token Authentication mechanism to call Blob store APIs

### ISSUE THREAD

**Issue by chandrashekar-s** [google-research/CVD-paper-mobile-camera-example#45]
Provide token based authentication mechanism for invoking cloud storage APIs.

**Comment by chandrashekar-s** [comment]
Refer to this [doc](https://docs.google.com/document/d/1yMaVMLBbSZ2PZBBcGbFFwgmF95Wb4ODqE3nxXb489vk/edit?resourcekey=0-AEebxCYcch9CImtzB0u4zQ#heading=h.71feuka3a8qw) for the implementation of the API.

**Comment by khyativyasargus** [comment]
@MJ1998 Need to expose Interface to set token for MinIO client to support token based authentication with external IDP.
Also can we have option to choose either token is bearer or not?

**Comment by MJ1998** [comment]
@khyativyasargus 

Above is first version of the PR.
How we are imagining this is to provide CredentialsProviderAuthenticator & CustomIDPAuthenticator interfaces which can be implemented by application layer for OpenIDP and custom IDP respectively. 

In your case you would need to implement the latter and provide the sdk with refreshed token, rolearn and duration in seconds.

**Comment by MJ1998** [comment]
This has been fixed by PR #54 . Closing this.

**Comment by MJ1998** [comment]
Pr is yet to be merged.
