### ISSUE TITLE
Need API for Status Access at activity level for UploadRequest

### ISSUE THREAD

**Issue by khyativyasargus** [google-research/CVD-paper-mobile-camera-example#47]
We will need API to have access to the status from UploadRequest at the activity level, so we can handle UI block till Upload is processed successfully and also handle the failure case.

@MJ1998

**Comment by MJ1998** [comment]
Why do you need to block UI while uploading?

Also do you need access to uploadrequest based on resourceInfoId (for example yoy know PPG resource is collected and has a resourceInfoId) OR the current uploadrequest based on status( for example status=UPLOADING for the current upload being processed)?

**Comment by khyativyasargus** [comment]
> Why do you need to block UI while uploading?
> 
> Also do you need access to uploadrequest based on resourceInfoId (for example yoy know PPG resource is collected and has a resourceInfoId) OR the current uploadrequest based on status( for example status=UPLOADING for the current upload being processed)?
> 
> If you need the latter then you will get List of UploadRequests with current status as UPLOADING which you can use to show on the UI or as some [app notification](https://www.tutlane.com/tutorial/android/android-progress-notification-with-examples#:~:text=Generally%2C%20the%20progress%20indicators%20in,and%20then%20issue%20the%20notification.)

In order to make sure the user doesn't close the app before data is uploaded successfully. 
We already have sync feature where we sync another data blocking UI with progressbar, so can include this Uploading as well as single upload thread for both.

Also we will only need it based on status.

**Comment by MJ1998** [comment]
I am not sure why user needs to keep the app open while uploading. 

Even if user needs to, showing a non-blocking UI is preferred over blocking UI to show progress update.
