### ISSUE TITLE
Improvise the Singleton pattern in SensingEngine

### ISSUE THREAD

**Issue by chandrashekar-s** [google-research/CVD-paper-mobile-camera-example#69]
Improve the Singleton pattern in this [class](https://github.com/google-research/CVD-paper-mobile-camera-example/blob/main/sensing/src/main/java/com/google/android/sensing/SensingEngineProvider.kt) and other places if needed as per the changes made in this [PR](**https://github.com/google-research/CVD-paper-mobile-camera-example/pull/61**)

**Comment by MJ1998** [comment]
Closing as fixed by #61 and #78
